### PR TITLE
Add simple surface rendering tutorial to gallery

### PR DESCRIPTION
**Pull request by anniegbryant**
This PR creates a few simple gallery images for surface rendering -- more to be added, this is just a starter

### CODE REVIEW

**Review by sina-mansour — CHANGES_REQUESTED** [review]
Actually, when "subcortex" is provided, the cerebellum and brainstem are excluded (the cortex will always be rendered).

This is because the [CIFTI format](https://www.humanconnectome.org/software/workbench-command/-cifti-help) stores information of the cerebellum, brainstem, and subcortex as volumes and the cortex as a surface. Hence, when the volumetric_structures is set to none only the surfaces are rendered, but subcortex, or all volumetric structures can also be added by changing the default.

Could you update the description to reflect this point (mainly plot_subcortex_surface.py, but to think of it the file names may also need changing).

**Comment by sina-mansour** [comment]
@kaitj Once this PR is merged, we have a few simple examples to put in the gallery.

**Review by anniegbryant — COMMENTED** [review]
Subcortex terminology has now been corrected

**Review by sina-mansour — APPROVED** [review]

**Review by sina-mansour — COMMENTED** [review]
Also, I just noticed the readthedocs checks fail (seems to be an import error -> cbv not found).

**Comment by sina-mansour** [comment]
Here are the logs from the checks:

```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v6.2.1
making output directory... done
Matplotlib is building the font cache; this may take a moment.
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
WARNING: html_static_path entry '_static' does not exist
generating gallery...
generating gallery for auto_examples... 
generating gallery for auto_examples/simple_surface_rendering... [ 33%] plot_all_surfaces.py
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_all_surfaces.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_all_surfaces.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined

generating gallery for auto_examples/simple_surface_rendering... [ 66%] plot_subcortex_surface.py
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_subcortex_surface.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_subcortex_surface.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined

generating gallery for auto_examples/simple_surface_rendering... [100%] plot_cortex_surface.py
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_cortex_surface.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_cortex_surface.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


computation time summary:
    - examples/simple_surface_rendering/plot_all_surfaces.py:        0.00 sec   0.0 MB
    - examples/simple_surface_rendering/plot_cortex_surface.py:      0.00 sec   0.0 MB
    - examples/simple_surface_rendering/plot_subcortex_surface.py:   0.00 sec   0.0 MB
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
myst v1.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'tasklist', 'attrs_block', 'deflist', 'attrs_inline', 'fieldlist'}, disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=['python', 'yaml'], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
[autosummary] generating autosummary for: api/utils.md, examples/README.md, general/main.md, index.md, tutorial/surface.md
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 5 source files that are out of date
updating environment: [new config] 11 added, 0 changed, 0 removed
reading sources... [  9%] api/utils
reading sources... [ 18%] auto_examples/index
reading sources... [ 27%] auto_examples/simple_surface_rendering/index
reading sources... [ 36%] auto_examples/simple_surface_rendering/plot_all_surfaces
reading sources... [ 45%] auto_examples/simple_surface_rendering/plot_cortex_surface
reading sources... [ 54%] auto_examples/simple_surface_rendering/plot_subcortex_surface
reading sources... [ 63%] auto_examples/simple_surface_rendering/sg_execution_times
reading sources... [ 72%] examples/README
reading sources... [ 81%] general/main
reading sources... [ 90%] index
reading sources... [100%] tutorial/surface

/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/api/utils.md:1: WARNING: Document headings start at H2, not H1 [myst.header]
WARNING: invalid signature for automodule ('cerebro.cerebro_brain_utils\n:members')
WARNING: don't know which module to import for autodocumenting 'cerebro.cerebro_brain_utils\n:members' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/index.rst:6: WARNING: Title underline too short.

Cerebro plotting examples
==================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/index.rst:21: WARNING: Title underline too short.

Simple surface rendering
==================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/index.rst:21: WARNING: Title underline too short.

Simple surface rendering
==================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/simple_surface_rendering/index.rst:6: WARNING: Title underline too short.

Simple surface rendering
==================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/simple_surface_rendering/plot_all_surfaces.rst:21: WARNING: Title overline too short.

================
Cortex, subcortex, cerebellum, and brainstem surface rendering
================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/simple_surface_rendering/plot_cortex_surface.rst:21: WARNING: Title overline too short.

================
Cortex surface rendering
================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/auto_examples/simple_surface_rendering/plot_subcortex_surface.rst:21: WARNING: Title overline too short.

================
Cortex and subcortex surface rendering
================
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/tutorial/surface.md:5: WARNING: Unknown directive type: 'python' [myst.directive_unknown]
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/api/utils.md: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/README.md: WARNING: document isn't included in any toctree
done
preparing documents... WARNING: unsupported theme option 'source_repository' given
WARNING: unsupported theme option 'source_branch' given
WARNING: unsupported theme option 'source_directory' given
done
writing output... [  9%] api/utils
writing output... [ 18%] auto_examples/index
writing output... [ 27%] auto_examples/simple_surface_rendering/index
writing output... [ 36%] auto_examples/simple_surface_rendering/plot_all_surfaces
writing output... [ 45%] auto_examples/simple_surface_rendering/plot_cortex_surface
writing output... [ 54%] auto_examples/simple_surface_rendering/plot_subcortex_surface
writing output... [ 63%] auto_examples/simple_surface_rendering/sg_execution_times
writing output... [ 72%] examples/README
writing output... [ 81%] general/main
writing output... [ 90%] index
writing output... [100%] tutorial/surface

/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/README.md:39: WARNING: 'myst' cross-reference target not found: 'Contributors.md' [myst.xref_missing]
generating indices... genindex done
writing additional pages... search done
copying images... [ 33%] auto_examples/simple_surface_rendering/images/thumb/sphx_glr_plot_all_surfaces_thumb.png
copying images... [ 66%] auto_examples/simple_surface_rendering/images/thumb/sphx_glr_plot_subcortex_surface_thumb.png
copying images... [100%] auto_examples/simple_surface_rendering/images/thumb/sphx_glr_plot_cortex_surface_thumb.png

copying downloadable files... [ 12%] auto_examples/auto_examples_python.zip
copying downloadable files... [ 25%] auto_examples/auto_examples_jupyter.zip
copying downloadable files... [ 37%] auto_examples/simple_surface_rendering/plot_all_surfaces.py
copying downloadable files... [ 50%] auto_examples/simple_surface_rendering/plot_all_surfaces.ipynb
copying downloadable files... [ 62%] auto_examples/simple_surface_rendering/plot_cortex_surface.py
copying downloadable files... [ 75%] auto_examples/simple_surface_rendering/plot_cortex_surface.ipynb
copying downloadable files... [ 87%] auto_examples/simple_surface_rendering/plot_subcortex_surface.py
copying downloadable files... [100%] auto_examples/simple_surface_rendering/plot_subcortex_surface.ipynb

copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
Updating searchtools for Read the Docs search... 
Sphinx-Gallery successfully executed 0 out of 3 files subselected by:

    gallery_conf["filename_pattern"] = '/plot_'
    gallery_conf["ignore_pattern"]   = '__init__\\.py'

after excluding 0 files that had previously been run (based on MD5).


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/envs/34/lib/python3.10/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/envs/34/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
    self.events.emit('build-finished', None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/envs/34/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/envs/34/lib/python3.10/site-packages/sphinx_gallery/gen_gallery.py", line 1113, in summarize_failing_examples
    raise ExtensionError(fail_message)
sphinx.errors.ExtensionError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_subcortex_surface.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_subcortex_surface.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_all_surfaces.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_all_surfaces.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_cortex_surface.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_cortex_surface.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


-------------------------------------------------------------------------------

Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_subcortex_surface.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_subcortex_surface.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_all_surfaces.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_all_surfaces.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_cortex_surface.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cerebro-viewer/checkouts/34/docs/examples/simple_surface_rendering/plot_cortex_surface.py", line 11, in <module>
    my_brain_viewer = cbv.Cerebro_brain_viewer(offscreen=True)
NameError: name 'cbv' is not defined


-------------------------------------------------------------------------------
Command time: 16s Return: 2
```

**Comment by anniegbryant** [comment]
Whoops -- forgot to copy the module import commands, fixed now

**Pull request merged**
